### ISSUE TITLE
Add posibility to always initialize Options to Some, Strings to nonEmpty

### ISSUE THREAD

**Issue by jauniusb** [wix-incubator/nutri-matic#3]

**Comment by laurynaslubys** [comment]
String length can be controlled with `.withStringLengths`. For `Option` you can define a custom generator 
```scala
Generators.byErasure[Option[_]]((t, r) => Some(r.makeComponent(t.typeArgs.head)))
``` 

This is a workable solution for now I would say, so closing this issue. Feel free to reopen if you disagree
